### ISSUE TITLE
Add Standard Library Support

### ISSUE THREAD

**Issue by sDos280** [ScriptLineStudios/waphics.c#3]
Hi, is there a way to get `C Standard Library` support, because i want to add some stuff to the library but i need some of the standard library functions (like malloc/free), is there a way to compile the wasm with with the `C Standard Library`?

**Comment by ScriptLineStudios** [comment]
I agree. Standard library support would be amazing. Our best option would be to look into this: https://wasi.dev/

**Comment by sDos280** [comment]
ok, thanks. i will look into that.

p.s. just found that: https://depth-first.com/articles/2019/10/16/compiling-c-to-webassembly-and-running-it-without-emscripten/

**Comment by ScriptLineStudios** [comment]
@sDos280 This looks promising, ill also take a look into it when i get time over the weekend :D

**Comment by sDos280** [comment]
@ScriptLineStudios i think i have another way of getting the standard library, we can compile waphic.c with [Emscripten](https://emscripten.org/). unfortunately, i wasn't able to hook the wasm file generated with Emscripten to the html.

p.s. i am correctly using `emcc main.c -s WASM=1 -s "EXPORTED_FUNCTIONS=['_init', '_run']" --no-entry -o output.wasm` to compile the main example. unfortunately i won't be able to help that much because i am not familiar with Javascript/Emscripten...

**Comment by sDos280** [comment]
That also seem promising

https://web.dev/emscripting-a-c-library/

**Comment by ScriptLineStudios** [comment]
@sDos280 emscripten looks like a very good option. :+1:

**Comment by ScriptLineStudios** [comment]
@sDos280 i have moved from clang to emscripten, this can now be closed
